% 2022-05-18 17:56:44.292546603

% number of test repetitions
nt = 1e4;
% number of grid cells per dimension
n = 100;
% p-values generated by the test
p = zeros(nt,1);
% domain side length (can be arbitrarily chosen, as the test is scale invariant)
L = 1;
% smoothing radius for the density estimate
nf = 5;
for idx=1:nt
	b = randn(n,n);
[issignificant,pn,stat,out] = periodogram_test_periodicity_2d(b, L, nf, bmsk, fmsk, ns, significance_level)
	[p(idx),ratio,maxShat,mdx,fdx,S] = periodogram_test_periodicity_2d( b, L, nf);
end
a = [0.01, 0.05, 0.1]
for idx=1:length(q)
	printf('Confidence level a = %g, Fraction of patterns with p>a: %g\n',a(idx),mean(p>a(idx)));
end

