% Fri 24 Feb 13:28:04 CET 2023
% std of the geometric brownian bridge
%B(t,T) = S(t) - (S(T)-S(0))*t/T
%       = S(t)*(1-t/T) - (S(T) - S(t) - S(0))*t/T
%Variance:
%var(B(t,T) = var(S(t))*(1-t/T)^2 + var(S(T-t))*(t/T)^2, by independence

function gsd = gbb_std(t,S0,T,r,sigma)
	%sd = hypot(gbm_std(t,r,sigma,S0).*(1-t/T),gbm_std(T-t,r,sigma,S0).*t/T);
	%s2 = (log(gbm_std(t,r,sigma,S0)).^2.*(1-t/T).^2) + (log(gbm_std(T-t,r,sigma,S0)).^2.*(t/T).^2);
	%sd = exp(sqrt(s2));
%	B  = exp(log(S(t)).*(1-t./T) - t./T.*log(S(T)./(S(t)*S0)));
%	lB = log(S(t)).*(1-t./T) - t./T.*log(S(T)./(S(t)*S0))
%
if (0)
	gsd = exp( sqrt(      ...
				...%  log(gbm_std(t,r,sigma,S0)).^2.*(1-t/T) ...
				...+ log(gbm_std(T-t,r,sigma,S0)).^2.*(t/T) ...
			       (log(gbm_geostd(t,r,sigma,1)).^2   - log(gbm_geomean(t,r,sigma,1)).^2).*((1-t./T)).^2 ...
 	                     + (log(gbm_geostd(T-t,r,sigma,1)).^2 - log(gbm_geomean(T-t,r,sigma,1)).^2).*(t/T).^2 ...
			     - -2*log(gbm_geomean(t,r,sigma,1)).*log(gbm_geomean(T-t,r,sigma,1)).*((1-t./T)).*(t/T) ...
 			   ...-2*(log(gbm_mean(t,r,sigma,1)).*(1-t./T).*log(gbm_mean(T-t,r,sigma,1)).*(t./T)) ...
 	                    ...+ log(gbm_mean(T-t,r,sigma,1)).^2.*(t./T).^2 ...
 ...			   % - log(gbm_mean(t,r,sigma,1)).*(1-t./T) ...
 ...	                   % + log(gbm_mean(T-t,r,sigma,1)).*(t./T) ...
 			  ) ...
	         );
end
	gsd = exp(sigma*sqrt(t.*(T-t)./T));
% var(S) = E[S^2] + E[S]^2 -> E[S^2] = std(S)^2-E[S]^2

end

