% Thu 23 Mar 10:51:00 CET 2017
% Karl Kastner, Berlin
%
%% powers of a continuous fourier series in sin/cos form
%%
%% powers of a^p = (ur + u1 sin(ot) + u2 sin(ot+dp))^p
%% phase of first component assumed 0
%%
%% frequencies higher than 2-omega ignored in input
%% frequencies higher than 3-omega not computed
%
% TODO use cos omega t !!!
function [ap c] = fourier_power(a,dp)
	a(end+1:3) = 0;
	a0 = a(1);
	a1 = a(2);
	a2 = a(3);
	dp = dp(1);

	% dimensions of output ap
	% first dimension  : frequency (mean, 1, 2, 3)
	% second dimension : sin,cos (imag,real)
	% last dimension   : power (1, 2, 3)
	
	%
	% first power a^1
	%
	% a^1 zero frequency term (mean)
	ap(1,1,1) = a0;
	ap(1,2,1) = 0; % (mean of a real time zeros has no second (imaginary) component)

	% a^1 diurnal
	ap(2,1,1) = a1;
	ap(2,2,1) = 0; % by definition of zero phase of input

	% a^1 semidiurnal
	ap(3,1,1) = a2*sin(dp);
	ap(3,2,1) = a2*sin(dp);

	% a^1 terdiurnal (zero, as input only has two species)
	ap(4,1,1) = 0;
	ap(4,2,1) = 0;

	%
	% second power a^2
	%

	% a^2 mean (zero frequency)
	% (u0 + u1 sin(x) + u2 sin(2x+dp) )^2  
	%                     = u0^2 + 2 u0 u1 sin(x) + 2u0 u2 sin(2x+dp) + 2 u1 u2 sin(x)sin(2x dp) + u1^2 sin(x)^2 + u2^2 sin(2x dp)^2
	%		      = ur^2 + 2 ur ut sin(a) + ut^2 (1/2 - 1/2 cos(2a))
	% note: there is no interaction in u2 with respect to the mean between D1 and D2,
	% if the chebycheff expansion is only computed until third order
	ap(1,1,2) = a0^2 + 1/2*a1^2 + 1/2*a2^2;
	ap(1,2,2) = 0;

	% a^2 diurnal component
	% a^2_1 = 2*a0*a1*sin(x) + a1*a2*cos(x + dp)
	%      = 2*a0*a1*sin(x) + a1*a2*(-sin(x)*sin(dp) + cos(x)*cos(dp))
	ap(2,1,2)  = 2*a0*a1 - a1*a2*sin(dp);
	ap(2,2,2)  = a1*a2*cos(dp);

	% a^2 semidiurnal component
	ap(3,1,2) = 2*a0*a2*cos(dp);		% first even overtide is damped by itself
	ap(3,2,2) = 2*a0*a2*sin(dp) - 1/2*a1^2;	% first overtide is generated by itself

	% a^2 terdiurnal component
	ap(4,1,2) =  a1*a2*sin(dp);
	ap(4,2,2) = -a1*a2*cos(dp);

	%
	% third power a^3
	%

	% a^3 zero frequency component (mean)
	ap(1,1,3) = a0^3 + 3/2*a0*a1^2 + 3/2*a0*a2^2 - 3/4*a1^2*a2*sin(dp);
	ap(1,2,3) = 0;

	% a^3 diurnal component
	% 3/4 because cos^3 = 1/4(3 cosx + 1 cos(3x))
	ap(2,1,3) = 3/4*a1^3   + 3*a0^2*a1 + 3/2*a1*a2^2 - 3*a0*a1*a2*sin(dp);
	ap(2,2,3) = 3*a0*a1*a2*cos(dp);

	% a^3 semidiurnal component
	ap(3,1,3) = cos(dp)*( 3/4*a2^3 + 3*a0^2*a2 + 3/2*a1^2*a2 );
	ap(3,2,3) = sin(dp)*( 3/4*a2^3 + 3*a0^2*a2 + 3/2*a1^2*a2 ) - 3/2*a0*a1^2;

	% a^3 terdiurnal component
	ap(4,1,3) = -1/4*a1^3 + 3/4*a1*a2^2*cos(2*dp) + 3*a0*a1*a2*sin(dp);
	ap(4,2,3) =  3/4*a1*a2^2*sin(2*dp) - 3*a0*a1*a2*cos(dp);

	c(:,1) = [ap(1,1,1) ap(2,1,1) ap(2,2,1) ap(3,1,1) ap(3,2,1) ap(4,1,1) ap(4,2,1)];
	c(:,2) = [ap(1,1,2) ap(2,1,2) ap(2,2,2) ap(3,1,2) ap(3,2,2) ap(4,1,2) ap(4,2,2)];
	c(:,3) = [ap(1,1,3) ap(2,1,3) ap(2,2,3) ap(3,1,3) ap(3,2,3) ap(4,1,3) ap(4,2,3)];
	%c(:,:,4) = [ap(1,1,4) ap(2,1,4) ap(2,2,4) ap(3,1,4) ap(3,2,4)];
end % fourier_power

